### ISSUE TITLE
templ dependency

### ISSUE THREAD

**Issue by gedw99** [zangster300/northstar#2]
I ran from your instructions on the README, just to have a play..

templ and pnpx are used but NOT installed.

you can instal these things in a .dep folder and path them and so not pollute a users laptop.
```
PATH := $PWD/.dep:$PATH

```

deno or bun can replace pnpx I think ? 

templ can be set to a "task dep", which checks via "which templ" and then will not try to install it again. its very fast to do this check. We assume everyone has which  :)

https://github.com/hairyhenderson/go-which can be part of "task dep" then so that all users get a which setup.

**Comment by zangster300** [comment]
I love the recommendations, but I actually have been trying to get the starter off as many installed deps as possible. 

I think it absolutely could make sense to have a .deps and install whatever into it, but I would rather devs have that be an opt-in feature rather than opting-out of dependencies

**Comment by zangster300** [comment]
> How are you going to remove deps from the starter ? curious on if you have a strategy.

For the go related deps I've switched over to using `go run [pkg]`

[Example for templ usage](https://github.com/zangster300/gonads-starter/blob/main/Taskfile.yml#L41)
https://github.com/zangster300/gonads-starter/blob/main/Taskfile.yml#L41)

Your feedback has led me to finding [this](https://www.npmjs.com/package/@pnpm/exe) as a possible bundled solution to using pnpm instead of a need to install it

I have personally not used bun yet, but will check it out

Currently NodeJS/pnpm are used in this project for 

1. Tailwind style gen
2. Using esbuild to bundle D* for usage in env's without an internet connection / creating debug builds
3. Bundling the lit-html web components

I would like to remove Node as a needed to be installed dep as much as possible!
