### ISSUE TITLE
Should the _templ.go files be added to .gitignore?

### ISSUE THREAD

**Issue by AndrooFrowns** [zangster300/northstar#5]
I think they're build artifacts that are generated at build time right?

**Comment by zangster300** [comment]
Yep! They are build artifacts generated by the `templ` runtime

I included them in the repo because I don't expect them to change often, but they absolutely could be removed.

The `build:templ` task (and live variant) will always regenerate them as well

[relevant discussion in the official templ repo](https://github.com/a-h/templ/discussions/419)

Will definitely consider removing them in a future commit
